export { default as LoginPage } from './LoginPage'
export { default as DashboardPage } from './DashboardPage'
export { default as AppointmentsPage } from './AppointmentsPage'
export { default as ResourcesPage } from './ResourcesPage'
export { default as ResourceDetailPage } from './ResourceDetailPage'
export { default as ServicesPage } from './ServicesPage'
export { default as GuestsPage } from './GuestsPage'
